services:
  nginx:
    depends_on:
      - api
      - client
    image: 'nginx:latest'
    # Ensure that nginx is always running even if it crashes
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - "3050:80"
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres_password   # pick any non-empty value
      - POSTGRES_DB=postgres
  redis:
    image: 'redis:latest'
  # changing this as server is a keyword in NGINX and it'll complicate things
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./server # this is used to tell where the Dockerfile.dev.dev is located ... use the source code in the "./server" folder to build the image
    volumes:
      - /app/node_modules # to avoid overwriting node_modules inside the container ... don't allow modifications of the container's app/node_modules folder
      - ./server:/app # copy the source code from the host machine's ./server folder to the container's /app folder
    depends_on:
      - postgres
      - redis
    environment:
      #      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/postgres
      #      - REDIS_URL=redis://redis:6379
      - REDIS_HOST=redis # we can use the name of the service as the hostname to connect to it
      - REDIS_PORT=6379
        # REDIS_PORT=6379 ---> https://hub.docker.com/_/redis ... we could always find the value there, but let's leave as default
      # PG details can be found on ---> https://hub.docker.com/_/postgres
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
  worker:
    build:
      dockerfile: Dockerfile.dev
      context: ./worker
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - /app/node_modules
      - ./worker:/app
  client:
    environment:
      - WDS_SOCKET_PORT=0
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
